# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-17 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='msg',
            field=models.TextField(max_length=500),
        ),
    ]
