# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-19 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giveawayentry',
            name='giveaway',
            field=models.PositiveIntegerField(verbose_name='Giveaway'),
        ),
        migrations.AlterField(
            model_name='giveawayentry',
            name='user',
            field=models.PositiveIntegerField(verbose_name='aut1h.User'),
        ),
    ]
