# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-19 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20170519_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giveawayentry',
            name='user',
            field=models.PositiveIntegerField(verbose_name='auth.User'),
        ),
    ]
